version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend  
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
