version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=demo_key
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
