#!/bin/bash

echo "🎬 Enterprise Chat Agent Demo"
echo ""
echo "This demo showcases:"
echo "• Multi-tenant WebSocket connections with authentication"
echo "• Real-time chat with AI responses (Gemini API integration)"
echo "• Tenant isolation and quota management"
echo "• Enterprise SSO simulation"
echo "• Real-time context synchronization"
echo ""
echo "Demo Steps:"
echo "1. Open http://localhost:3000"
echo "2. Select organization (Acme Corp or TechStart Inc)"
echo "3. Choose user type and sign in via SSO"
echo "4. Start chatting with the AI assistant"
echo "5. Open multiple browser tabs to see multi-user sync"
echo "6. Check different tenant isolation by switching organizations"
echo ""
echo "Monitor the backend logs to see:"
echo "• WebSocket connections and tenant isolation"
echo "• Message processing and quota enforcement"
echo "• Real-time context synchronization events"
echo ""
echo "API endpoints to test:"
echo "• GET http://localhost:8000/health - Health check"
echo "• GET http://localhost:8000/tenant/info - Tenant information (requires auth)"
echo "• POST http://localhost:8000/conversations - Create conversation (requires auth)"
echo ""
echo "For production deployment:"
echo "• Configure real SSO provider (SAML/OIDC)"
echo "• Set up proper SSL certificates"
echo "• Configure load balancing for WebSocket scaling"
echo "• Implement comprehensive monitoring and logging"
